### ISSUE TITLE
localhost not working on windows

### ISSUE THREAD

**Issue by mimcomp** [yoonbae81/yQuant#20]
my debug-log
 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:457:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
5 verbose cwd C:\pyscript\venu\app\yQuant
6 error Windows_NT 10.0.15063
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v6.11.3
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
 also
npm WARN yquant@1.0.0 No repository field.
how to run yquant on windows ?

**Comment by yoonbae81** [comment]
Hello,
yQuant doesn't have starting point yet. The only way you could start it is to run mocha test in /test directory. You will need Redis as well.

**Comment by mimcomp** [comment]
I installed it Redis  and mocha but not run with command mocha test not found the file but with npm test
is ok with some errors:- 
C:\pyscript\venu\app\yQuant\test>npm test

> yquant@1.0.0 test C:\pyscript\venu\app\yQuant
> mocha

C:\pyscript\venu\app\yQuant\test\manager.js:37
  beforeEach(async function() {
             ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\pyscript\venu\app\yQuant\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\pyscript\venu\app\yQuant\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\pyscript\venu\app\yQuant\node_modules\mocha\lib\mocha.js:514:10)
    at Object.<anonymous> (C:\pyscript\venu\app\yQuant\node_modules\mocha\bin\_mocha:480:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
npm ERR! Test failed.  See above for more details.

**Comment by yoonbae81** [comment]
yQuant uses async/await features which are supported by Node v8 and you need to install mocha for global (npm -g install mocha) for mocha testing in command line ($ mocha) or your IDE. I hope this will solve your difficulty.
